name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  cached_network_image: ^3.4.1

  # State management & navigation
  flutter_riverpod: ^2.3.6
  go_router: ^17.0.0

  # Data handling
  http: ^1.2.2
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  intl: ^0.20.2

  # Local storage
  shared_preferences: ^2.3.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.0

  # Firebase & Auth
  firebase_core: ^4.2.0
  firebase_analytics: ^12.0.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.0.1

  # Maps
  google_maps_flutter: ^2.9.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  freezed: ^3.1.0
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true

